// Paths map to the WebP variants generated by `npm run images` (scripts/optimize-images.mjs).
const WIDTHS = [640, 1280, 1920];

export const imageSet = (path) => ({
  src: `/images/${path}-1280.webp`,
  srcSet: WIDTHS.map((w) => `/images/${path}-${w}.webp ${w}w`).join(', '),
});

export const imageUrl = (path, width = 640) => `/images/${path}-${width}.webp`;
